Q1 (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 4, 5])

In [1]:
import numpy as np
arr = np.array([1,2,3,6,4,5])
ans= arr[::-1]
print("the array answer ", ans)

the array answer  [5 4 6 3 2 1]


Q1 (b) Flatten the NumPy array: array1 = np.array([[1, 2], [3, 4]])

In [2]:
import numpy as np
arr1= np.array([[1,2,3], [2,4,5], [1,2,3]])
flat= arr1.flatten()
print("flattened", flat)

flattened [1 2 3 2 4 5 1 2 3]


Q1 (c) Compare the following numpy arrays using any two methods

In [3]:
import numpy as np
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[1,2],[3,4]])
comparison = arr1== arr2
print("comparing", comparison)

comparing [[ True  True]
 [ True  True]]


Q1 (d) Find the most frequent value and their indice(s)
i. x = np.array([1, 2, 2, 3, 1, 1, 2])
ii. y = np.array([5, 1, 5, 3, 5, 2, 2])

In [4]:
x = np.array([1, 2, 2, 3, 1, 1, 2])
y = np.array([5, 1, 5, 3, 5, 2, 2])
most_freq_x = np.bincount(x).argmax()
indices_x = np.where(x == most_freq_x)[0]
most_freq_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_y)[0]

Q1 (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [5]:
import numpy as np
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
ans1=np.sum(gfg)
ans2= np.sum(gfg,axis=1)
ans3 = np.sum(gfg,axis=0)
print(ans1,ans2,ans3)

45 [[14]
 [16]
 [15]] [[20  9 16]]


Q1 (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [6]:

import numpy as np
n_array = np.array([[55,25,15], [30,44,2],[11,45,77]])
dia = np.trace(n_array)
eig= np.linalg.eigvals(n_array)
print(dia, eig)


eig, vec= np.linalg.eig(n_array)
det= np.linalg.det(n_array)
inverse = np.linalg.inv(n_array)
print (dia,eig,vec,inverse,det)


176 [98.16835147 28.097044   49.73460452]
176 [98.16835147 28.097044   49.73460452] [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]] [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 137180.0000000001


Q1 (g) Multiply matrices and find covariance
i. p = [[1, 2], [2, 3]]; q = [[4, 5], [6, 7]]

In [7]:
import numpy as np
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
cov1 = np.cov(p1.T, q1.T)

print(product1)
print(cov1)

[[16 19]
 [26 31]]
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


ii. p = [[1, 2], [2, 3], [4, 5]]; q = [[4, 5, 1], [6, 7, 2]]

In [8]:

import numpy as np

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())


print(product2)
print(cov2)

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


Q1 (h) For matrices x and y, find inner, outer and cartesian product

In [9]:
import numpy as np

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
outer_product = np.outer(x, y)
cartesian_product = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print("inner:", inner_product)
print("outer:" , outer_product)
print("cartesian:", cartesian_product)

inner: [[17 52]
 [13 62]]
outer: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
cartesian: [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2 (a) For array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Element-wise absolute value
ii. Percentiles
iii. Statistics

In [10]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
percentiles_flat = np.percentile(array.flatten(), [25, 50, 75])
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("\nPercentiles (flat):", percentiles_flat)
print("Percentiles (columns):\n", percentiles_col)
print("Percentiles (rows):\n", percentiles_row)
print("\nMean (flat):", mean_flat)
print("Median (flat):", median_flat)
print("Std (flat):", std_flat)
print("\nMean (columns):", mean_col)
print("Median (columns):", median_col)
print("Std (columns):", std_col)
print("\nMean (rows):", mean_row)
print("Median (rows):", median_row)
print("Std (rows):", std_row)


Percentiles (flat): [-3.5 -0.5  2.5]
Percentiles (columns):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (rows):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean (flat): -0.5
Median (flat): -0.5
Std (flat): 3.8622100754188224

Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Std (columns): [2.5 3.5 4.5]

Mean (rows): [ 0.66666667 -1.66666667]
Median (rows): [ 1. -4.]
Std (rows): [2.05480467 4.78423336]


Q2 (b) For array: a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

In [11]:

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
rounded_vals = np.round(a)
print(" Original array:", a)
print("Floor values:", floor_vals)
print("Ceil values:", ceil_vals)
print("Truncated values:", trunc_vals)
print("Rounded values:", rounded_vals)

 Original array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceil values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]
